import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/angularpractice/');
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.locator('app-card').filter({ hasText: 'iphone X $24.99 Lorem ipsum' }).getByRole('button').click();
  await page.locator('app-card').filter({ hasText: 'Samsung Note 8 $24.99 Lorem' }).click();
  await page.getByText('Checkout ( 1 ) (current)').click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('i');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('in');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('ind');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('indi');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).fill('india');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).press('BrowserFavorites');
  await page.getByText('India').click();
  await page.getByText('I agree with the term &').click();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await expect(page.getByText('× Success! Thank you! Your')).toBeVisible();
  await page.getByText('Please choose your delivery').click();
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).click();
  await page.getByRole('button', { name: 'Purchase' }).click();
});